module.exports = {
    utilitiesSidebar: [
        "introduction",
        {
            type: "category",
            label: "Utilities",
            collapsible: true,
            collapsed: false,
            items: [
                {
                    type: "autogenerated",
                    dirName: "utilities",
                },
            ],
        },
        {
            type: "category",
            label: "React Hooks",
            collapsible: true,
            collapsed: false,
            items: [
                {
                    type: "autogenerated",
                    dirName: "hooks",
                },
            ],
        },
    ],
};
