name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.16.1
            - name: Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: pnpm
            - run: pnpm i
            # - run: npx playwright install-deps
            - run: pnpm test
